/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

#ifdef HAVE_CONFIG_H
#  include <config.h>
#endif

#include <sys/types.h>
#include <sys/stat.h>
#include <unistd.h>
#include <string.h>
#include <stdio.h>

#include <gdk/gdkkeysyms.h>
#include <gtk/gtk.h>

#include "callbacks.h"
#include "interface.h"
#include "support.h"

#define GLADE_HOOKUP_OBJECT(component,widget,name) \
  g_object_set_data_full (G_OBJECT (component), name, \
    gtk_widget_ref (widget), (GDestroyNotify) gtk_widget_unref)

#define GLADE_HOOKUP_OBJECT_NO_REF(component,widget,name) \
  g_object_set_data (G_OBJECT (component), name, widget)

GtkWidget*
create_windowGestionMenu (void)
{
  GtkWidget *windowGestionMenu;
  GtkWidget *fixed1;
  GtkWidget *buttonAcceuil1;
  GtkWidget *alignment1;
  GtkWidget *hbox1;
  GtkWidget *image1;
  GtkWidget *label1;
  GtkWidget *buttonDeconnexin1;
  GtkWidget *alignment2;
  GtkWidget *hbox2;
  GtkWidget *image2;
  GtkWidget *label2;
  GtkWidget *buttonAjoutMenu;
  GtkWidget *alignment3;
  GtkWidget *hbox3;
  GtkWidget *image3;
  GtkWidget *label3;
  GtkWidget *buttonModifmenu;
  GtkWidget *alignment4;
  GtkWidget *hbox4;
  GtkWidget *image4;
  GtkWidget *label4;
  GtkWidget *image34;
  GtkWidget *buttonSupprimeMenu;
  GtkWidget *alignment5;
  GtkWidget *hbox5;
  GtkWidget *image5;
  GtkWidget *label5;
  GtkWidget *button16;
  GtkWidget *alignment24;
  GtkWidget *hbox24;
  GtkWidget *image24;
  GtkWidget *label121;
  GtkWidget *meilleur_m;
  GtkWidget *alignment32;
  GtkWidget *hbox32;
  GtkWidget *image33;
  GtkWidget *label131;

  windowGestionMenu = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_widget_set_size_request (windowGestionMenu, 1000, 600);
  gtk_window_set_title (GTK_WINDOW (windowGestionMenu), _("Gestion des menus"));

  fixed1 = gtk_fixed_new ();
  gtk_widget_show (fixed1);
  gtk_container_add (GTK_CONTAINER (windowGestionMenu), fixed1);

  buttonAcceuil1 = gtk_button_new ();
  gtk_widget_show (buttonAcceuil1);
  gtk_fixed_put (GTK_FIXED (fixed1), buttonAcceuil1, 856, 16);
  gtk_widget_set_size_request (buttonAcceuil1, 120, 40);

  alignment1 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment1);
  gtk_container_add (GTK_CONTAINER (buttonAcceuil1), alignment1);

  hbox1 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox1);
  gtk_container_add (GTK_CONTAINER (alignment1), hbox1);

  image1 = gtk_image_new_from_stock ("gtk-home", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image1);
  gtk_box_pack_start (GTK_BOX (hbox1), image1, FALSE, FALSE, 0);

  label1 = gtk_label_new_with_mnemonic (_("Acceuil"));
  gtk_widget_show (label1);
  gtk_box_pack_start (GTK_BOX (hbox1), label1, FALSE, FALSE, 0);

  buttonDeconnexin1 = gtk_button_new ();
  gtk_widget_show (buttonDeconnexin1);
  gtk_fixed_put (GTK_FIXED (fixed1), buttonDeconnexin1, 856, 80);
  gtk_widget_set_size_request (buttonDeconnexin1, 120, 40);

  alignment2 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment2);
  gtk_container_add (GTK_CONTAINER (buttonDeconnexin1), alignment2);

  hbox2 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox2);
  gtk_container_add (GTK_CONTAINER (alignment2), hbox2);

  image2 = gtk_image_new_from_stock ("gtk-dialog-authentication", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image2);
  gtk_box_pack_start (GTK_BOX (hbox2), image2, FALSE, FALSE, 0);

  label2 = gtk_label_new_with_mnemonic (_("Quitter"));
  gtk_widget_show (label2);
  gtk_box_pack_start (GTK_BOX (hbox2), label2, FALSE, FALSE, 0);

  buttonAjoutMenu = gtk_button_new ();
  gtk_widget_show (buttonAjoutMenu);
  gtk_fixed_put (GTK_FIXED (fixed1), buttonAjoutMenu, 392, 112);
  gtk_widget_set_size_request (buttonAjoutMenu, 192, 64);

  alignment3 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment3);
  gtk_container_add (GTK_CONTAINER (buttonAjoutMenu), alignment3);

  hbox3 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox3);
  gtk_container_add (GTK_CONTAINER (alignment3), hbox3);

  image3 = gtk_image_new_from_stock ("gtk-add", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image3);
  gtk_box_pack_start (GTK_BOX (hbox3), image3, FALSE, FALSE, 0);

  label3 = gtk_label_new_with_mnemonic (_("Ajouter un menu"));
  gtk_widget_show (label3);
  gtk_box_pack_start (GTK_BOX (hbox3), label3, FALSE, FALSE, 0);

  buttonModifmenu = gtk_button_new ();
  gtk_widget_show (buttonModifmenu);
  gtk_fixed_put (GTK_FIXED (fixed1), buttonModifmenu, 392, 208);
  gtk_widget_set_size_request (buttonModifmenu, 192, 64);

  alignment4 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment4);
  gtk_container_add (GTK_CONTAINER (buttonModifmenu), alignment4);

  hbox4 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox4);
  gtk_container_add (GTK_CONTAINER (alignment4), hbox4);

  image4 = gtk_image_new_from_stock ("gtk-edit", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image4);
  gtk_box_pack_start (GTK_BOX (hbox4), image4, FALSE, FALSE, 0);

  label4 = gtk_label_new_with_mnemonic (_(" Modifier un menu"));
  gtk_widget_show (label4);
  gtk_box_pack_start (GTK_BOX (hbox4), label4, FALSE, FALSE, 0);

  image34 = create_pixmap (windowGestionMenu, "index.png");
  gtk_widget_show (image34);
  gtk_fixed_put (GTK_FIXED (fixed1), image34, 376, 0);
  gtk_widget_set_size_request (image34, 224, 88);

  buttonSupprimeMenu = gtk_button_new ();
  gtk_widget_show (buttonSupprimeMenu);
  gtk_fixed_put (GTK_FIXED (fixed1), buttonSupprimeMenu, 392, 312);
  gtk_widget_set_size_request (buttonSupprimeMenu, 192, 64);

  alignment5 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment5);
  gtk_container_add (GTK_CONTAINER (buttonSupprimeMenu), alignment5);

  hbox5 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox5);
  gtk_container_add (GTK_CONTAINER (alignment5), hbox5);

  image5 = gtk_image_new_from_stock ("gtk-remove", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image5);
  gtk_box_pack_start (GTK_BOX (hbox5), image5, FALSE, FALSE, 0);

  label5 = gtk_label_new_with_mnemonic (_("Supprimer un menu"));
  gtk_widget_show (label5);
  gtk_box_pack_start (GTK_BOX (hbox5), label5, FALSE, FALSE, 0);

  button16 = gtk_button_new ();
  gtk_widget_show (button16);
  gtk_fixed_put (GTK_FIXED (fixed1), button16, 392, 416);
  gtk_widget_set_size_request (button16, 192, 64);

  alignment24 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment24);
  gtk_container_add (GTK_CONTAINER (button16), alignment24);

  hbox24 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox24);
  gtk_container_add (GTK_CONTAINER (alignment24), hbox24);

  image24 = gtk_image_new_from_stock ("gtk-justify-fill", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image24);
  gtk_box_pack_start (GTK_BOX (hbox24), image24, FALSE, FALSE, 0);

  label121 = gtk_label_new_with_mnemonic (_("Liste des menus"));
  gtk_widget_show (label121);
  gtk_box_pack_start (GTK_BOX (hbox24), label121, FALSE, FALSE, 0);

  meilleur_m = gtk_button_new ();
  gtk_widget_show (meilleur_m);
  gtk_fixed_put (GTK_FIXED (fixed1), meilleur_m, 392, 520);
  gtk_widget_set_size_request (meilleur_m, 192, 64);

  alignment32 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment32);
  gtk_container_add (GTK_CONTAINER (meilleur_m), alignment32);

  hbox32 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox32);
  gtk_container_add (GTK_CONTAINER (alignment32), hbox32);

  image33 = gtk_image_new_from_stock ("gtk-about", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image33);
  gtk_box_pack_start (GTK_BOX (hbox32), image33, FALSE, FALSE, 0);

  label131 = gtk_label_new_with_mnemonic (_("Meilleur menu"));
  gtk_widget_show (label131);
  gtk_box_pack_start (GTK_BOX (hbox32), label131, FALSE, FALSE, 0);

  g_signal_connect ((gpointer) buttonAcceuil1, "clicked",
                    G_CALLBACK (on_buttonAcceuil_clicked),
                    NULL);
  g_signal_connect ((gpointer) buttonDeconnexin1, "clicked",
                    G_CALLBACK (on_buttonDeconnexin_clicked),
                    NULL);
  g_signal_connect ((gpointer) buttonAjoutMenu, "clicked",
                    G_CALLBACK (on_buttonAjoutMenu_clicked),
                    NULL);
  g_signal_connect ((gpointer) buttonModifmenu, "clicked",
                    G_CALLBACK (on_buttonModifMenu_clicked),
                    NULL);
  g_signal_connect ((gpointer) buttonSupprimeMenu, "clicked",
                    G_CALLBACK (on_buttonSupprimeMenu_clicked),
                    NULL);
  g_signal_connect ((gpointer) button16, "clicked",
                    G_CALLBACK (on_button16_clicked),
                    NULL);
  g_signal_connect ((gpointer) meilleur_m, "clicked",
                    G_CALLBACK (on_afficher_meuilleur_m_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (windowGestionMenu, windowGestionMenu, "windowGestionMenu");
  GLADE_HOOKUP_OBJECT (windowGestionMenu, fixed1, "fixed1");
  GLADE_HOOKUP_OBJECT (windowGestionMenu, buttonAcceuil1, "buttonAcceuil1");
  GLADE_HOOKUP_OBJECT (windowGestionMenu, alignment1, "alignment1");
  GLADE_HOOKUP_OBJECT (windowGestionMenu, hbox1, "hbox1");
  GLADE_HOOKUP_OBJECT (windowGestionMenu, image1, "image1");
  GLADE_HOOKUP_OBJECT (windowGestionMenu, label1, "label1");
  GLADE_HOOKUP_OBJECT (windowGestionMenu, buttonDeconnexin1, "buttonDeconnexin1");
  GLADE_HOOKUP_OBJECT (windowGestionMenu, alignment2, "alignment2");
  GLADE_HOOKUP_OBJECT (windowGestionMenu, hbox2, "hbox2");
  GLADE_HOOKUP_OBJECT (windowGestionMenu, image2, "image2");
  GLADE_HOOKUP_OBJECT (windowGestionMenu, label2, "label2");
  GLADE_HOOKUP_OBJECT (windowGestionMenu, buttonAjoutMenu, "buttonAjoutMenu");
  GLADE_HOOKUP_OBJECT (windowGestionMenu, alignment3, "alignment3");
  GLADE_HOOKUP_OBJECT (windowGestionMenu, hbox3, "hbox3");
  GLADE_HOOKUP_OBJECT (windowGestionMenu, image3, "image3");
  GLADE_HOOKUP_OBJECT (windowGestionMenu, label3, "label3");
  GLADE_HOOKUP_OBJECT (windowGestionMenu, buttonModifmenu, "buttonModifmenu");
  GLADE_HOOKUP_OBJECT (windowGestionMenu, alignment4, "alignment4");
  GLADE_HOOKUP_OBJECT (windowGestionMenu, hbox4, "hbox4");
  GLADE_HOOKUP_OBJECT (windowGestionMenu, image4, "image4");
  GLADE_HOOKUP_OBJECT (windowGestionMenu, label4, "label4");
  GLADE_HOOKUP_OBJECT (windowGestionMenu, image34, "image34");
  GLADE_HOOKUP_OBJECT (windowGestionMenu, buttonSupprimeMenu, "buttonSupprimeMenu");
  GLADE_HOOKUP_OBJECT (windowGestionMenu, alignment5, "alignment5");
  GLADE_HOOKUP_OBJECT (windowGestionMenu, hbox5, "hbox5");
  GLADE_HOOKUP_OBJECT (windowGestionMenu, image5, "image5");
  GLADE_HOOKUP_OBJECT (windowGestionMenu, label5, "label5");
  GLADE_HOOKUP_OBJECT (windowGestionMenu, button16, "button16");
  GLADE_HOOKUP_OBJECT (windowGestionMenu, alignment24, "alignment24");
  GLADE_HOOKUP_OBJECT (windowGestionMenu, hbox24, "hbox24");
  GLADE_HOOKUP_OBJECT (windowGestionMenu, image24, "image24");
  GLADE_HOOKUP_OBJECT (windowGestionMenu, label121, "label121");
  GLADE_HOOKUP_OBJECT (windowGestionMenu, meilleur_m, "meilleur_m");
  GLADE_HOOKUP_OBJECT (windowGestionMenu, alignment32, "alignment32");
  GLADE_HOOKUP_OBJECT (windowGestionMenu, hbox32, "hbox32");
  GLADE_HOOKUP_OBJECT (windowGestionMenu, image33, "image33");
  GLADE_HOOKUP_OBJECT (windowGestionMenu, label131, "label131");

  return windowGestionMenu;
}

GtkWidget*
create_ModifierMenu (void)
{
  GtkWidget *ModifierMenu;
  GtkWidget *fixed6;
  GtkWidget *entryMOdifierId;
  GtkObject *spinbuttonJours_adj;
  GtkWidget *spinbuttonJours;
  GtkObject *spinbuttonMois_adj;
  GtkWidget *spinbuttonMois;
  GtkObject *spinbuttonAnnees_adj;
  GtkWidget *spinbuttonAnnees;
  GtkWidget *entryModifierRepas;
  GtkWidget *entryModifierQD;
  GtkWidget *label25;
  GtkWidget *label26;
  GtkWidget *label28;
  GtkWidget *label27;
  GtkWidget *label31;
  GtkWidget *label99;
  GtkWidget *label98;
  GtkWidget *checkbuttonModifierHumidite;
  GtkWidget *checkbuttonModifierDejeuner;
  GtkWidget *button18retouuuur;
  GtkWidget *alignment31;
  GtkWidget *hbox31;
  GtkWidget *image31;
  GtkWidget *label129;
  GtkWidget *buttonConfirmerModif;
  GtkWidget *alignment19;
  GtkWidget *hbox19;
  GtkWidget *image19;
  GtkWidget *label29;

  ModifierMenu = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_widget_set_size_request (ModifierMenu, 400, 400);
  gtk_window_set_title (GTK_WINDOW (ModifierMenu), _("ModifierMenu"));

  fixed6 = gtk_fixed_new ();
  gtk_widget_show (fixed6);
  gtk_container_add (GTK_CONTAINER (ModifierMenu), fixed6);

  entryMOdifierId = gtk_entry_new ();
  gtk_widget_show (entryMOdifierId);
  gtk_fixed_put (GTK_FIXED (fixed6), entryMOdifierId, 160, 48);
  gtk_widget_set_size_request (entryMOdifierId, 160, 28);
  gtk_entry_set_invisible_char (GTK_ENTRY (entryMOdifierId), 8226);

  spinbuttonJours_adj = gtk_adjustment_new (1, 1, 31, 1, 10, 10);
  spinbuttonJours = gtk_spin_button_new (GTK_ADJUSTMENT (spinbuttonJours_adj), 1, 0);
  gtk_widget_show (spinbuttonJours);
  gtk_fixed_put (GTK_FIXED (fixed6), spinbuttonJours, 104, 104);
  gtk_widget_set_size_request (spinbuttonJours, 80, 24);

  spinbuttonMois_adj = gtk_adjustment_new (1, 1, 12, 1, 10, 10);
  spinbuttonMois = gtk_spin_button_new (GTK_ADJUSTMENT (spinbuttonMois_adj), 1, 0);
  gtk_widget_show (spinbuttonMois);
  gtk_fixed_put (GTK_FIXED (fixed6), spinbuttonMois, 192, 104);
  gtk_widget_set_size_request (spinbuttonMois, 80, 24);

  spinbuttonAnnees_adj = gtk_adjustment_new (2021, 1990, 2050, 1, 10, 10);
  spinbuttonAnnees = gtk_spin_button_new (GTK_ADJUSTMENT (spinbuttonAnnees_adj), 1, 0);
  gtk_widget_show (spinbuttonAnnees);
  gtk_fixed_put (GTK_FIXED (fixed6), spinbuttonAnnees, 280, 104);
  gtk_widget_set_size_request (spinbuttonAnnees, 80, 24);

  entryModifierRepas = gtk_entry_new ();
  gtk_widget_show (entryModifierRepas);
  gtk_fixed_put (GTK_FIXED (fixed6), entryModifierRepas, 168, 152);
  gtk_widget_set_size_request (entryModifierRepas, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entryModifierRepas), 8226);

  entryModifierQD = gtk_entry_new ();
  gtk_widget_show (entryModifierQD);
  gtk_fixed_put (GTK_FIXED (fixed6), entryModifierQD, 168, 256);
  gtk_widget_set_size_request (entryModifierQD, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entryModifierQD), 8226);

  label25 = gtk_label_new (_("ID"));
  gtk_widget_show (label25);
  gtk_fixed_put (GTK_FIXED (fixed6), label25, 32, 48);
  gtk_widget_set_size_request (label25, 100, 32);
  gtk_label_set_use_markup (GTK_LABEL (label25), TRUE);

  label26 = gtk_label_new (_("Date"));
  gtk_widget_show (label26);
  gtk_fixed_put (GTK_FIXED (fixed6), label26, 32, 96);
  gtk_widget_set_size_request (label26, 88, 40);
  gtk_label_set_use_markup (GTK_LABEL (label26), TRUE);

  label28 = gtk_label_new (_("Type"));
  gtk_widget_show (label28);
  gtk_fixed_put (GTK_FIXED (fixed6), label28, 24, 200);
  gtk_widget_set_size_request (label28, 120, 40);
  gtk_label_set_use_markup (GTK_LABEL (label28), TRUE);

  label27 = gtk_label_new (_("Repas"));
  gtk_widget_show (label27);
  gtk_fixed_put (GTK_FIXED (fixed6), label27, 32, 152);
  gtk_widget_set_size_request (label27, 120, 32);
  gtk_label_set_use_markup (GTK_LABEL (label27), TRUE);

  label31 = gtk_label_new (_("QD"));
  gtk_widget_show (label31);
  gtk_fixed_put (GTK_FIXED (fixed6), label31, 32, 256);
  gtk_widget_set_size_request (label31, 88, 32);
  gtk_label_set_use_markup (GTK_LABEL (label31), TRUE);

  label99 = gtk_label_new (_("Dejeuner"));
  gtk_widget_show (label99);
  gtk_fixed_put (GTK_FIXED (fixed6), label99, 152, 200);
  gtk_widget_set_size_request (label99, 88, 40);
  gtk_label_set_use_markup (GTK_LABEL (label99), TRUE);

  label98 = gtk_label_new (_("Diner"));
  gtk_widget_show (label98);
  gtk_fixed_put (GTK_FIXED (fixed6), label98, 272, 200);
  gtk_widget_set_size_request (label98, 96, 40);
  gtk_label_set_use_markup (GTK_LABEL (label98), TRUE);

  checkbuttonModifierHumidite = gtk_check_button_new_with_mnemonic ("");
  gtk_widget_show (checkbuttonModifierHumidite);
  gtk_fixed_put (GTK_FIXED (fixed6), checkbuttonModifierHumidite, 248, 208);
  gtk_widget_set_size_request (checkbuttonModifierHumidite, 40, 24);

  checkbuttonModifierDejeuner = gtk_check_button_new_with_mnemonic ("");
  gtk_widget_show (checkbuttonModifierDejeuner);
  gtk_fixed_put (GTK_FIXED (fixed6), checkbuttonModifierDejeuner, 128, 208);
  gtk_widget_set_size_request (checkbuttonModifierDejeuner, 48, 24);

  button18retouuuur = gtk_button_new ();
  gtk_widget_show (button18retouuuur);
  gtk_fixed_put (GTK_FIXED (fixed6), button18retouuuur, 272, 320);
  gtk_widget_set_size_request (button18retouuuur, 82, 37);

  alignment31 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment31);
  gtk_container_add (GTK_CONTAINER (button18retouuuur), alignment31);

  hbox31 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox31);
  gtk_container_add (GTK_CONTAINER (alignment31), hbox31);

  image31 = gtk_image_new_from_stock ("gtk-go-back", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image31);
  gtk_box_pack_start (GTK_BOX (hbox31), image31, FALSE, FALSE, 0);

  label129 = gtk_label_new_with_mnemonic (_("Retour"));
  gtk_widget_show (label129);
  gtk_box_pack_start (GTK_BOX (hbox31), label129, FALSE, FALSE, 0);

  buttonConfirmerModif = gtk_button_new ();
  gtk_widget_show (buttonConfirmerModif);
  gtk_fixed_put (GTK_FIXED (fixed6), buttonConfirmerModif, 144, 320);
  gtk_widget_set_size_request (buttonConfirmerModif, 100, 40);
  gtk_container_set_border_width (GTK_CONTAINER (buttonConfirmerModif), 1);

  alignment19 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment19);
  gtk_container_add (GTK_CONTAINER (buttonConfirmerModif), alignment19);

  hbox19 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox19);
  gtk_container_add (GTK_CONTAINER (alignment19), hbox19);

  image19 = gtk_image_new_from_stock ("gtk-apply", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image19);
  gtk_box_pack_start (GTK_BOX (hbox19), image19, FALSE, FALSE, 0);

  label29 = gtk_label_new_with_mnemonic (_("Confirmer"));
  gtk_widget_show (label29);
  gtk_box_pack_start (GTK_BOX (hbox19), label29, FALSE, FALSE, 0);

  g_signal_connect ((gpointer) checkbuttonModifierHumidite, "toggled",
                    G_CALLBACK (on_checkbuttonDiner_toggled),
                    NULL);
  g_signal_connect ((gpointer) checkbuttonModifierDejeuner, "toggled",
                    G_CALLBACK (on_checkbuttonDejeuner_toggled),
                    NULL);
  g_signal_connect ((gpointer) button18retouuuur, "clicked",
                    G_CALLBACK (on_button18retouuuur_clicked),
                    NULL);
  g_signal_connect ((gpointer) buttonConfirmerModif, "clicked",
                    G_CALLBACK (on_buttonConfirmerModif_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (ModifierMenu, ModifierMenu, "ModifierMenu");
  GLADE_HOOKUP_OBJECT (ModifierMenu, fixed6, "fixed6");
  GLADE_HOOKUP_OBJECT (ModifierMenu, entryMOdifierId, "entryMOdifierId");
  GLADE_HOOKUP_OBJECT (ModifierMenu, spinbuttonJours, "spinbuttonJours");
  GLADE_HOOKUP_OBJECT (ModifierMenu, spinbuttonMois, "spinbuttonMois");
  GLADE_HOOKUP_OBJECT (ModifierMenu, spinbuttonAnnees, "spinbuttonAnnees");
  GLADE_HOOKUP_OBJECT (ModifierMenu, entryModifierRepas, "entryModifierRepas");
  GLADE_HOOKUP_OBJECT (ModifierMenu, entryModifierQD, "entryModifierQD");
  GLADE_HOOKUP_OBJECT (ModifierMenu, label25, "label25");
  GLADE_HOOKUP_OBJECT (ModifierMenu, label26, "label26");
  GLADE_HOOKUP_OBJECT (ModifierMenu, label28, "label28");
  GLADE_HOOKUP_OBJECT (ModifierMenu, label27, "label27");
  GLADE_HOOKUP_OBJECT (ModifierMenu, label31, "label31");
  GLADE_HOOKUP_OBJECT (ModifierMenu, label99, "label99");
  GLADE_HOOKUP_OBJECT (ModifierMenu, label98, "label98");
  GLADE_HOOKUP_OBJECT (ModifierMenu, checkbuttonModifierHumidite, "checkbuttonModifierHumidite");
  GLADE_HOOKUP_OBJECT (ModifierMenu, checkbuttonModifierDejeuner, "checkbuttonModifierDejeuner");
  GLADE_HOOKUP_OBJECT (ModifierMenu, button18retouuuur, "button18retouuuur");
  GLADE_HOOKUP_OBJECT (ModifierMenu, alignment31, "alignment31");
  GLADE_HOOKUP_OBJECT (ModifierMenu, hbox31, "hbox31");
  GLADE_HOOKUP_OBJECT (ModifierMenu, image31, "image31");
  GLADE_HOOKUP_OBJECT (ModifierMenu, label129, "label129");
  GLADE_HOOKUP_OBJECT (ModifierMenu, buttonConfirmerModif, "buttonConfirmerModif");
  GLADE_HOOKUP_OBJECT (ModifierMenu, alignment19, "alignment19");
  GLADE_HOOKUP_OBJECT (ModifierMenu, hbox19, "hbox19");
  GLADE_HOOKUP_OBJECT (ModifierMenu, image19, "image19");
  GLADE_HOOKUP_OBJECT (ModifierMenu, label29, "label29");

  return ModifierMenu;
}

GtkWidget*
create_dialog1 (void)
{
  GtkWidget *dialog1;
  GtkWidget *dialog_vbox1;
  GtkWidget *fixed7;
  GtkWidget *label33;
  GtkWidget *dialog_action_area1;
  GtkWidget *okbutton1;

  dialog1 = gtk_dialog_new ();
  gtk_widget_set_size_request (dialog1, 310, 200);
  gtk_window_set_title (GTK_WINDOW (dialog1), _("dialog1"));
  gtk_window_set_type_hint (GTK_WINDOW (dialog1), GDK_WINDOW_TYPE_HINT_DIALOG);
  gtk_dialog_set_has_separator (GTK_DIALOG (dialog1), FALSE);

  dialog_vbox1 = GTK_DIALOG (dialog1)->vbox;
  gtk_widget_show (dialog_vbox1);

  fixed7 = gtk_fixed_new ();
  gtk_widget_show (fixed7);
  gtk_box_pack_start (GTK_BOX (dialog_vbox1), fixed7, TRUE, TRUE, 0);

  label33 = gtk_label_new_with_mnemonic (_("<span foreground=\"#f936\" ><b>menu ajout\303\251 avec succ\303\251es !</b></span>"));
  gtk_widget_show (label33);
  gtk_fixed_put (GTK_FIXED (fixed7), label33, 40, 40);
  gtk_widget_set_size_request (label33, 212, 100);
  gtk_label_set_use_markup (GTK_LABEL (label33), TRUE);

  dialog_action_area1 = GTK_DIALOG (dialog1)->action_area;
  gtk_widget_show (dialog_action_area1);
  gtk_button_box_set_layout (GTK_BUTTON_BOX (dialog_action_area1), GTK_BUTTONBOX_END);

  okbutton1 = gtk_button_new_from_stock ("gtk-ok");
  gtk_widget_show (okbutton1);
  gtk_dialog_add_action_widget (GTK_DIALOG (dialog1), okbutton1, GTK_RESPONSE_OK);
  GTK_WIDGET_SET_FLAGS (okbutton1, GTK_CAN_DEFAULT);

  g_signal_connect ((gpointer) okbutton1, "clicked",
                    G_CALLBACK (on_okbutton1_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (dialog1, dialog1, "dialog1");
  GLADE_HOOKUP_OBJECT_NO_REF (dialog1, dialog_vbox1, "dialog_vbox1");
  GLADE_HOOKUP_OBJECT (dialog1, fixed7, "fixed7");
  GLADE_HOOKUP_OBJECT (dialog1, label33, "label33");
  GLADE_HOOKUP_OBJECT_NO_REF (dialog1, dialog_action_area1, "dialog_action_area1");
  GLADE_HOOKUP_OBJECT (dialog1, okbutton1, "okbutton1");

  return dialog1;
}

GtkWidget*
create_dialog2 (void)
{
  GtkWidget *dialog2;
  GtkWidget *dialog_vbox2;
  GtkWidget *fixed8;
  GtkWidget *label34;
  GtkWidget *dialog_action_area2;
  GtkWidget *okbutton2;

  dialog2 = gtk_dialog_new ();
  gtk_widget_set_size_request (dialog2, 310, 200);
  gtk_window_set_title (GTK_WINDOW (dialog2), _("dialog2"));
  gtk_window_set_type_hint (GTK_WINDOW (dialog2), GDK_WINDOW_TYPE_HINT_DIALOG);
  gtk_dialog_set_has_separator (GTK_DIALOG (dialog2), FALSE);

  dialog_vbox2 = GTK_DIALOG (dialog2)->vbox;
  gtk_widget_show (dialog_vbox2);

  fixed8 = gtk_fixed_new ();
  gtk_widget_show (fixed8);
  gtk_box_pack_start (GTK_BOX (dialog_vbox2), fixed8, TRUE, TRUE, 0);

  label34 = gtk_label_new_with_mnemonic (_("<span foreground=\"#f936\"><b>Menu modifi\303\251 avec succ\303\251e</b></span> "));
  gtk_widget_show (label34);
  gtk_fixed_put (GTK_FIXED (fixed8), label34, 40, 40);
  gtk_widget_set_size_request (label34, 211, 77);
  gtk_label_set_use_markup (GTK_LABEL (label34), TRUE);

  dialog_action_area2 = GTK_DIALOG (dialog2)->action_area;
  gtk_widget_show (dialog_action_area2);
  gtk_button_box_set_layout (GTK_BUTTON_BOX (dialog_action_area2), GTK_BUTTONBOX_END);

  okbutton2 = gtk_button_new_from_stock ("gtk-ok");
  gtk_widget_show (okbutton2);
  gtk_dialog_add_action_widget (GTK_DIALOG (dialog2), okbutton2, GTK_RESPONSE_OK);
  GTK_WIDGET_SET_FLAGS (okbutton2, GTK_CAN_DEFAULT);

  g_signal_connect ((gpointer) okbutton2, "clicked",
                    G_CALLBACK (on_okbutton2_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (dialog2, dialog2, "dialog2");
  GLADE_HOOKUP_OBJECT_NO_REF (dialog2, dialog_vbox2, "dialog_vbox2");
  GLADE_HOOKUP_OBJECT (dialog2, fixed8, "fixed8");
  GLADE_HOOKUP_OBJECT (dialog2, label34, "label34");
  GLADE_HOOKUP_OBJECT_NO_REF (dialog2, dialog_action_area2, "dialog_action_area2");
  GLADE_HOOKUP_OBJECT (dialog2, okbutton2, "okbutton2");

  return dialog2;
}

GtkWidget*
create_dialog3 (void)
{
  GtkWidget *dialog3;
  GtkWidget *dialog_vbox3;
  GtkWidget *fixed9;
  GtkWidget *label35;
  GtkWidget *dialog_action_area3;
  GtkWidget *okbutton3;

  dialog3 = gtk_dialog_new ();
  gtk_widget_set_size_request (dialog3, 310, 200);
  gtk_window_set_title (GTK_WINDOW (dialog3), _("dialog3"));
  gtk_window_set_type_hint (GTK_WINDOW (dialog3), GDK_WINDOW_TYPE_HINT_DIALOG);
  gtk_dialog_set_has_separator (GTK_DIALOG (dialog3), FALSE);

  dialog_vbox3 = GTK_DIALOG (dialog3)->vbox;
  gtk_widget_show (dialog_vbox3);

  fixed9 = gtk_fixed_new ();
  gtk_widget_show (fixed9);
  gtk_box_pack_start (GTK_BOX (dialog_vbox3), fixed9, TRUE, TRUE, 0);

  label35 = gtk_label_new_with_mnemonic (_("<span foreground=\"#f936\"><b>Menu supprim\303\251 avec succ\303\251e</b></span>"));
  gtk_widget_show (label35);
  gtk_fixed_put (GTK_FIXED (fixed9), label35, 40, 40);
  gtk_widget_set_size_request (label35, 225, 40);
  gtk_label_set_use_markup (GTK_LABEL (label35), TRUE);

  dialog_action_area3 = GTK_DIALOG (dialog3)->action_area;
  gtk_widget_show (dialog_action_area3);
  gtk_button_box_set_layout (GTK_BUTTON_BOX (dialog_action_area3), GTK_BUTTONBOX_END);

  okbutton3 = gtk_button_new_from_stock ("gtk-ok");
  gtk_widget_show (okbutton3);
  gtk_dialog_add_action_widget (GTK_DIALOG (dialog3), okbutton3, GTK_RESPONSE_OK);
  GTK_WIDGET_SET_FLAGS (okbutton3, GTK_CAN_DEFAULT);

  g_signal_connect ((gpointer) okbutton3, "clicked",
                    G_CALLBACK (on_okbutton3_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (dialog3, dialog3, "dialog3");
  GLADE_HOOKUP_OBJECT_NO_REF (dialog3, dialog_vbox3, "dialog_vbox3");
  GLADE_HOOKUP_OBJECT (dialog3, fixed9, "fixed9");
  GLADE_HOOKUP_OBJECT (dialog3, label35, "label35");
  GLADE_HOOKUP_OBJECT_NO_REF (dialog3, dialog_action_area3, "dialog_action_area3");
  GLADE_HOOKUP_OBJECT (dialog3, okbutton3, "okbutton3");

  return dialog3;
}

GtkWidget*
create_windowRemplir (void)
{
  GtkWidget *windowRemplir;
  GtkWidget *dialog_vbox4;
  GtkWidget *fixed10;
  GtkWidget *label36;
  GtkWidget *dialog_action_area4;
  GtkWidget *okbutton4;

  windowRemplir = gtk_dialog_new ();
  gtk_widget_set_size_request (windowRemplir, 310, 200);
  gtk_window_set_title (GTK_WINDOW (windowRemplir), _("Remplissage"));
  gtk_window_set_type_hint (GTK_WINDOW (windowRemplir), GDK_WINDOW_TYPE_HINT_DIALOG);
  gtk_dialog_set_has_separator (GTK_DIALOG (windowRemplir), FALSE);

  dialog_vbox4 = GTK_DIALOG (windowRemplir)->vbox;
  gtk_widget_show (dialog_vbox4);

  fixed10 = gtk_fixed_new ();
  gtk_widget_show (fixed10);
  gtk_box_pack_start (GTK_BOX (dialog_vbox4), fixed10, TRUE, TRUE, 0);

  label36 = gtk_label_new (_("<span foreground=\"#FF0404\" ><b>Veuillez remplir tous les champs</b></span>"));
  gtk_widget_show (label36);
  gtk_fixed_put (GTK_FIXED (fixed10), label36, 40, 40);
  gtk_widget_set_size_request (label36, 235, 40);
  gtk_label_set_use_markup (GTK_LABEL (label36), TRUE);

  dialog_action_area4 = GTK_DIALOG (windowRemplir)->action_area;
  gtk_widget_show (dialog_action_area4);
  gtk_button_box_set_layout (GTK_BUTTON_BOX (dialog_action_area4), GTK_BUTTONBOX_END);

  okbutton4 = gtk_button_new_from_stock ("gtk-ok");
  gtk_widget_show (okbutton4);
  gtk_dialog_add_action_widget (GTK_DIALOG (windowRemplir), okbutton4, GTK_RESPONSE_OK);
  GTK_WIDGET_SET_FLAGS (okbutton4, GTK_CAN_DEFAULT);

  g_signal_connect ((gpointer) okbutton4, "clicked",
                    G_CALLBACK (on_okbutton4_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (windowRemplir, windowRemplir, "windowRemplir");
  GLADE_HOOKUP_OBJECT_NO_REF (windowRemplir, dialog_vbox4, "dialog_vbox4");
  GLADE_HOOKUP_OBJECT (windowRemplir, fixed10, "fixed10");
  GLADE_HOOKUP_OBJECT (windowRemplir, label36, "label36");
  GLADE_HOOKUP_OBJECT_NO_REF (windowRemplir, dialog_action_area4, "dialog_action_area4");
  GLADE_HOOKUP_OBJECT (windowRemplir, okbutton4, "okbutton4");

  return windowRemplir;
}

GtkWidget*
create_windowAjoutMenu (void)
{
  GtkWidget *windowAjoutMenu;
  GtkWidget *fixed12;
  GtkWidget *entryId_ajout;
  GtkObject *spinbuttonJours_ajout_adj;
  GtkWidget *spinbuttonJours_ajout;
  GtkObject *spinbuttonMois_ajout_adj;
  GtkWidget *spinbuttonMois_ajout;
  GtkObject *spinbuttonAnnees_ajout_adj;
  GtkWidget *spinbuttonAnnees_ajout;
  GtkWidget *entryRepas_ajout;
  GtkWidget *entryQD_ajout;
  GtkWidget *label10;
  GtkWidget *label9;
  GtkWidget *label113;
  GtkWidget *label112;
  GtkWidget *label30;
  GtkWidget *label119;
  GtkWidget *radiobutton1_ajout;
  GSList *radiobutton1_ajout_group = NULL;
  GtkWidget *radiobutton2_ajout;
  GtkWidget *label120;
  GtkWidget *buttonAjouter;
  GtkWidget *alignment23;
  GtkWidget *hbox23;
  GtkWidget *image23;
  GtkWidget *label118;
  GtkWidget *buttonRetouur;
  GtkWidget *alignment26;
  GtkWidget *hbox26;
  GtkWidget *image26;
  GtkWidget *label123;

  windowAjoutMenu = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_widget_set_size_request (windowAjoutMenu, 400, 400);
  gtk_window_set_title (GTK_WINDOW (windowAjoutMenu), _("Ajouter des menus"));

  fixed12 = gtk_fixed_new ();
  gtk_widget_show (fixed12);
  gtk_container_add (GTK_CONTAINER (windowAjoutMenu), fixed12);

  entryId_ajout = gtk_entry_new ();
  gtk_widget_show (entryId_ajout);
  gtk_fixed_put (GTK_FIXED (fixed12), entryId_ajout, 160, 48);
  gtk_widget_set_size_request (entryId_ajout, 160, 28);
  gtk_entry_set_invisible_char (GTK_ENTRY (entryId_ajout), 8226);

  spinbuttonJours_ajout_adj = gtk_adjustment_new (8, 1, 31, 1, 10, 10);
  spinbuttonJours_ajout = gtk_spin_button_new (GTK_ADJUSTMENT (spinbuttonJours_ajout_adj), 1, 0);
  gtk_widget_show (spinbuttonJours_ajout);
  gtk_fixed_put (GTK_FIXED (fixed12), spinbuttonJours_ajout, 104, 104);
  gtk_widget_set_size_request (spinbuttonJours_ajout, 80, 24);

  spinbuttonMois_ajout_adj = gtk_adjustment_new (5, 1, 12, 1, 10, 10);
  spinbuttonMois_ajout = gtk_spin_button_new (GTK_ADJUSTMENT (spinbuttonMois_ajout_adj), 1, 0);
  gtk_widget_show (spinbuttonMois_ajout);
  gtk_fixed_put (GTK_FIXED (fixed12), spinbuttonMois_ajout, 192, 104);
  gtk_widget_set_size_request (spinbuttonMois_ajout, 80, 24);

  spinbuttonAnnees_ajout_adj = gtk_adjustment_new (2020, 1990, 2050, 1, 10, 10);
  spinbuttonAnnees_ajout = gtk_spin_button_new (GTK_ADJUSTMENT (spinbuttonAnnees_ajout_adj), 1, 0);
  gtk_widget_show (spinbuttonAnnees_ajout);
  gtk_fixed_put (GTK_FIXED (fixed12), spinbuttonAnnees_ajout, 280, 104);
  gtk_widget_set_size_request (spinbuttonAnnees_ajout, 80, 24);

  entryRepas_ajout = gtk_entry_new ();
  gtk_widget_show (entryRepas_ajout);
  gtk_fixed_put (GTK_FIXED (fixed12), entryRepas_ajout, 168, 152);
  gtk_widget_set_size_request (entryRepas_ajout, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entryRepas_ajout), 8226);

  entryQD_ajout = gtk_entry_new ();
  gtk_widget_show (entryQD_ajout);
  gtk_fixed_put (GTK_FIXED (fixed12), entryQD_ajout, 168, 256);
  gtk_widget_set_size_request (entryQD_ajout, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entryQD_ajout), 8226);

  label10 = gtk_label_new (_("Date"));
  gtk_widget_show (label10);
  gtk_fixed_put (GTK_FIXED (fixed12), label10, 32, 96);
  gtk_widget_set_size_request (label10, 88, 40);
  gtk_label_set_use_markup (GTK_LABEL (label10), TRUE);

  label9 = gtk_label_new (_("ID"));
  gtk_widget_show (label9);
  gtk_fixed_put (GTK_FIXED (fixed12), label9, 32, 48);
  gtk_widget_set_size_request (label9, 100, 32);
  gtk_label_set_use_markup (GTK_LABEL (label9), TRUE);

  label113 = gtk_label_new (_("Type"));
  gtk_widget_show (label113);
  gtk_fixed_put (GTK_FIXED (fixed12), label113, 24, 192);
  gtk_widget_set_size_request (label113, 128, 48);
  gtk_label_set_use_markup (GTK_LABEL (label113), TRUE);

  label112 = gtk_label_new (_("Repas"));
  gtk_widget_show (label112);
  gtk_fixed_put (GTK_FIXED (fixed12), label112, 32, 152);
  gtk_widget_set_size_request (label112, 120, 32);
  gtk_label_set_use_markup (GTK_LABEL (label112), TRUE);

  label30 = gtk_label_new (_("QD"));
  gtk_widget_show (label30);
  gtk_fixed_put (GTK_FIXED (fixed12), label30, 32, 256);
  gtk_widget_set_size_request (label30, 88, 32);
  gtk_label_set_use_markup (GTK_LABEL (label30), TRUE);

  label119 = gtk_label_new (_("Dejeuner"));
  gtk_widget_show (label119);
  gtk_fixed_put (GTK_FIXED (fixed12), label119, 160, 208);
  gtk_widget_set_size_request (label119, 105, 16);

  radiobutton1_ajout = gtk_radio_button_new_with_mnemonic (NULL, "");
  gtk_widget_show (radiobutton1_ajout);
  gtk_fixed_put (GTK_FIXED (fixed12), radiobutton1_ajout, 136, 208);
  gtk_widget_set_size_request (radiobutton1_ajout, 24, 16);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (radiobutton1_ajout), radiobutton1_ajout_group);
  radiobutton1_ajout_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (radiobutton1_ajout));

  radiobutton2_ajout = gtk_radio_button_new_with_mnemonic (NULL, "");
  gtk_widget_show (radiobutton2_ajout);
  gtk_fixed_put (GTK_FIXED (fixed12), radiobutton2_ajout, 264, 208);
  gtk_widget_set_size_request (radiobutton2_ajout, 16, 16);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (radiobutton2_ajout), radiobutton1_ajout_group);
  radiobutton1_ajout_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (radiobutton2_ajout));

  label120 = gtk_label_new (_("Diner"));
  gtk_widget_show (label120);
  gtk_fixed_put (GTK_FIXED (fixed12), label120, 288, 208);
  gtk_widget_set_size_request (label120, 72, 17);

  buttonAjouter = gtk_button_new ();
  gtk_widget_show (buttonAjouter);
  gtk_fixed_put (GTK_FIXED (fixed12), buttonAjouter, 232, 320);
  gtk_widget_set_size_request (buttonAjouter, 128, 40);
  gtk_container_set_border_width (GTK_CONTAINER (buttonAjouter), 1);

  alignment23 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment23);
  gtk_container_add (GTK_CONTAINER (buttonAjouter), alignment23);

  hbox23 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox23);
  gtk_container_add (GTK_CONTAINER (alignment23), hbox23);

  image23 = gtk_image_new_from_stock ("gtk-apply", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image23);
  gtk_box_pack_start (GTK_BOX (hbox23), image23, FALSE, FALSE, 0);

  label118 = gtk_label_new_with_mnemonic (_("Ajouter"));
  gtk_widget_show (label118);
  gtk_box_pack_start (GTK_BOX (hbox23), label118, FALSE, FALSE, 0);

  buttonRetouur = gtk_button_new ();
  gtk_widget_show (buttonRetouur);
  gtk_fixed_put (GTK_FIXED (fixed12), buttonRetouur, 72, 320);
  gtk_widget_set_size_request (buttonRetouur, 120, 37);

  alignment26 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment26);
  gtk_container_add (GTK_CONTAINER (buttonRetouur), alignment26);

  hbox26 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox26);
  gtk_container_add (GTK_CONTAINER (alignment26), hbox26);

  image26 = gtk_image_new_from_stock ("gtk-undo", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image26);
  gtk_box_pack_start (GTK_BOX (hbox26), image26, FALSE, FALSE, 0);

  label123 = gtk_label_new_with_mnemonic (_("Retour"));
  gtk_widget_show (label123);
  gtk_box_pack_start (GTK_BOX (hbox26), label123, FALSE, FALSE, 0);

  g_signal_connect ((gpointer) radiobutton1_ajout, "toggled",
                    G_CALLBACK (on_radiobutton1_toggled),
                    NULL);
  g_signal_connect ((gpointer) radiobutton2_ajout, "toggled",
                    G_CALLBACK (on_radiobutton2_toggled),
                    NULL);
  g_signal_connect ((gpointer) buttonAjouter, "clicked",
                    G_CALLBACK (on_buttonAjouter_clicked),
                    NULL);
  g_signal_connect ((gpointer) buttonRetouur, "clicked",
                    G_CALLBACK (on_buttonRetouur_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (windowAjoutMenu, windowAjoutMenu, "windowAjoutMenu");
  GLADE_HOOKUP_OBJECT (windowAjoutMenu, fixed12, "fixed12");
  GLADE_HOOKUP_OBJECT (windowAjoutMenu, entryId_ajout, "entryId_ajout");
  GLADE_HOOKUP_OBJECT (windowAjoutMenu, spinbuttonJours_ajout, "spinbuttonJours_ajout");
  GLADE_HOOKUP_OBJECT (windowAjoutMenu, spinbuttonMois_ajout, "spinbuttonMois_ajout");
  GLADE_HOOKUP_OBJECT (windowAjoutMenu, spinbuttonAnnees_ajout, "spinbuttonAnnees_ajout");
  GLADE_HOOKUP_OBJECT (windowAjoutMenu, entryRepas_ajout, "entryRepas_ajout");
  GLADE_HOOKUP_OBJECT (windowAjoutMenu, entryQD_ajout, "entryQD_ajout");
  GLADE_HOOKUP_OBJECT (windowAjoutMenu, label10, "label10");
  GLADE_HOOKUP_OBJECT (windowAjoutMenu, label9, "label9");
  GLADE_HOOKUP_OBJECT (windowAjoutMenu, label113, "label113");
  GLADE_HOOKUP_OBJECT (windowAjoutMenu, label112, "label112");
  GLADE_HOOKUP_OBJECT (windowAjoutMenu, label30, "label30");
  GLADE_HOOKUP_OBJECT (windowAjoutMenu, label119, "label119");
  GLADE_HOOKUP_OBJECT (windowAjoutMenu, radiobutton1_ajout, "radiobutton1_ajout");
  GLADE_HOOKUP_OBJECT (windowAjoutMenu, radiobutton2_ajout, "radiobutton2_ajout");
  GLADE_HOOKUP_OBJECT (windowAjoutMenu, label120, "label120");
  GLADE_HOOKUP_OBJECT (windowAjoutMenu, buttonAjouter, "buttonAjouter");
  GLADE_HOOKUP_OBJECT (windowAjoutMenu, alignment23, "alignment23");
  GLADE_HOOKUP_OBJECT (windowAjoutMenu, hbox23, "hbox23");
  GLADE_HOOKUP_OBJECT (windowAjoutMenu, image23, "image23");
  GLADE_HOOKUP_OBJECT (windowAjoutMenu, label118, "label118");
  GLADE_HOOKUP_OBJECT (windowAjoutMenu, buttonRetouur, "buttonRetouur");
  GLADE_HOOKUP_OBJECT (windowAjoutMenu, alignment26, "alignment26");
  GLADE_HOOKUP_OBJECT (windowAjoutMenu, hbox26, "hbox26");
  GLADE_HOOKUP_OBJECT (windowAjoutMenu, image26, "image26");
  GLADE_HOOKUP_OBJECT (windowAjoutMenu, label123, "label123");

  return windowAjoutMenu;
}

GtkWidget*
create_ListeMenus (void)
{
  GtkWidget *ListeMenus;
  GtkWidget *fixed13;
  GtkWidget *treeview;
  GtkWidget *buttonRetour;
  GtkWidget *alignment25;
  GtkWidget *hbox25;
  GtkWidget *image25;
  GtkWidget *label122;

  ListeMenus = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (ListeMenus), _("Liste des menus"));

  fixed13 = gtk_fixed_new ();
  gtk_widget_show (fixed13);
  gtk_container_add (GTK_CONTAINER (ListeMenus), fixed13);

  treeview = gtk_tree_view_new ();
  gtk_widget_show (treeview);
  gtk_fixed_put (GTK_FIXED (fixed13), treeview, 8, 16);
  gtk_widget_set_size_request (treeview, 432, 272);

  buttonRetour = gtk_button_new ();
  gtk_widget_show (buttonRetour);
  gtk_fixed_put (GTK_FIXED (fixed13), buttonRetour, 40, 288);
  gtk_widget_set_size_request (buttonRetour, 352, 37);

  alignment25 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment25);
  gtk_container_add (GTK_CONTAINER (buttonRetour), alignment25);

  hbox25 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox25);
  gtk_container_add (GTK_CONTAINER (alignment25), hbox25);

  image25 = gtk_image_new_from_stock ("gtk-undo", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image25);
  gtk_box_pack_start (GTK_BOX (hbox25), image25, FALSE, FALSE, 0);

  label122 = gtk_label_new_with_mnemonic (_("Retour"));
  gtk_widget_show (label122);
  gtk_box_pack_start (GTK_BOX (hbox25), label122, FALSE, FALSE, 0);

  g_signal_connect ((gpointer) treeview, "row_activated",
                    G_CALLBACK (on_treeview_row_activated),
                    NULL);
  g_signal_connect ((gpointer) buttonRetour, "clicked",
                    G_CALLBACK (on_buttonRetour_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (ListeMenus, ListeMenus, "ListeMenus");
  GLADE_HOOKUP_OBJECT (ListeMenus, fixed13, "fixed13");
  GLADE_HOOKUP_OBJECT (ListeMenus, treeview, "treeview");
  GLADE_HOOKUP_OBJECT (ListeMenus, buttonRetour, "buttonRetour");
  GLADE_HOOKUP_OBJECT (ListeMenus, alignment25, "alignment25");
  GLADE_HOOKUP_OBJECT (ListeMenus, hbox25, "hbox25");
  GLADE_HOOKUP_OBJECT (ListeMenus, image25, "image25");
  GLADE_HOOKUP_OBJECT (ListeMenus, label122, "label122");

  return ListeMenus;
}

GtkWidget*
create_windowSupprimeMenu (void)
{
  GtkWidget *windowSupprimeMenu;
  GtkWidget *fixed15;
  GtkWidget *entryID;
  GtkWidget *buttonReeeeeeeeetour;
  GtkWidget *alignment29;
  GtkWidget *hbox29;
  GtkWidget *image29;
  GtkWidget *label127;
  GtkWidget *label126;
  GtkWidget *buttonSupprimer;
  GtkWidget *alignment30;
  GtkWidget *hbox30;
  GtkWidget *image30;
  GtkWidget *label128;

  windowSupprimeMenu = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (windowSupprimeMenu), _("Supprimer un capteur"));

  fixed15 = gtk_fixed_new ();
  gtk_widget_show (fixed15);
  gtk_container_add (GTK_CONTAINER (windowSupprimeMenu), fixed15);

  entryID = gtk_entry_new ();
  gtk_widget_show (entryID);
  gtk_fixed_put (GTK_FIXED (fixed15), entryID, 152, 120);
  gtk_widget_set_size_request (entryID, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entryID), 8226);

  buttonReeeeeeeeetour = gtk_button_new ();
  gtk_widget_show (buttonReeeeeeeeetour);
  gtk_fixed_put (GTK_FIXED (fixed15), buttonReeeeeeeeetour, 112, 200);
  gtk_widget_set_size_request (buttonReeeeeeeeetour, 96, 32);

  alignment29 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment29);
  gtk_container_add (GTK_CONTAINER (buttonReeeeeeeeetour), alignment29);

  hbox29 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox29);
  gtk_container_add (GTK_CONTAINER (alignment29), hbox29);

  image29 = gtk_image_new_from_stock ("gtk-undo", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image29);
  gtk_box_pack_start (GTK_BOX (hbox29), image29, FALSE, FALSE, 0);

  label127 = gtk_label_new_with_mnemonic (_("Retour"));
  gtk_widget_show (label127);
  gtk_box_pack_start (GTK_BOX (hbox29), label127, FALSE, FALSE, 0);

  label126 = gtk_label_new (_("ID"));
  gtk_widget_show (label126);
  gtk_fixed_put (GTK_FIXED (fixed15), label126, 64, 112);
  gtk_widget_set_size_request (label126, 88, 48);

  buttonSupprimer = gtk_button_new ();
  gtk_widget_show (buttonSupprimer);
  gtk_fixed_put (GTK_FIXED (fixed15), buttonSupprimer, 240, 200);
  gtk_widget_set_size_request (buttonSupprimer, 104, 32);

  alignment30 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment30);
  gtk_container_add (GTK_CONTAINER (buttonSupprimer), alignment30);

  hbox30 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox30);
  gtk_container_add (GTK_CONTAINER (alignment30), hbox30);

  image30 = gtk_image_new_from_stock ("gtk-cancel", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image30);
  gtk_box_pack_start (GTK_BOX (hbox30), image30, FALSE, FALSE, 0);

  label128 = gtk_label_new_with_mnemonic (_("Supprimer"));
  gtk_widget_show (label128);
  gtk_box_pack_start (GTK_BOX (hbox30), label128, FALSE, FALSE, 0);

  g_signal_connect ((gpointer) buttonReeeeeeeeetour, "clicked",
                    G_CALLBACK (on_buttonReeeeeeeeetour_clicked),
                    NULL);
  g_signal_connect ((gpointer) buttonSupprimer, "clicked",
                    G_CALLBACK (on_buttonSupprimer_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (windowSupprimeMenu, windowSupprimeMenu, "windowSupprimeMenu");
  GLADE_HOOKUP_OBJECT (windowSupprimeMenu, fixed15, "fixed15");
  GLADE_HOOKUP_OBJECT (windowSupprimeMenu, entryID, "entryID");
  GLADE_HOOKUP_OBJECT (windowSupprimeMenu, buttonReeeeeeeeetour, "buttonReeeeeeeeetour");
  GLADE_HOOKUP_OBJECT (windowSupprimeMenu, alignment29, "alignment29");
  GLADE_HOOKUP_OBJECT (windowSupprimeMenu, hbox29, "hbox29");
  GLADE_HOOKUP_OBJECT (windowSupprimeMenu, image29, "image29");
  GLADE_HOOKUP_OBJECT (windowSupprimeMenu, label127, "label127");
  GLADE_HOOKUP_OBJECT (windowSupprimeMenu, label126, "label126");
  GLADE_HOOKUP_OBJECT (windowSupprimeMenu, buttonSupprimer, "buttonSupprimer");
  GLADE_HOOKUP_OBJECT (windowSupprimeMenu, alignment30, "alignment30");
  GLADE_HOOKUP_OBJECT (windowSupprimeMenu, hbox30, "hbox30");
  GLADE_HOOKUP_OBJECT (windowSupprimeMenu, image30, "image30");
  GLADE_HOOKUP_OBJECT (windowSupprimeMenu, label128, "label128");

  return windowSupprimeMenu;
}

GtkWidget*
create_meilleur (void)
{
  GtkWidget *meilleur;
  GtkWidget *fixed16;
  GtkWidget *label130;
  GtkWidget *label132;
  GtkWidget *scrolledwindow1;
  GtkWidget *treeview2_nutrition;
  GtkWidget *button_afficher_meilleur_M;

  meilleur = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (meilleur), _("Meilleur"));

  fixed16 = gtk_fixed_new ();
  gtk_widget_show (fixed16);
  gtk_container_add (GTK_CONTAINER (meilleur), fixed16);

  label130 = gtk_label_new ("");
  gtk_widget_show (label130);
  gtk_fixed_put (GTK_FIXED (fixed16), label130, 136, 192);
  gtk_widget_set_size_request (label130, 192, 56);

  label132 = gtk_label_new ("");
  gtk_widget_show (label132);
  gtk_fixed_put (GTK_FIXED (fixed16), label132, 160, 24);
  gtk_widget_set_size_request (label132, 232, 40);

  scrolledwindow1 = gtk_scrolled_window_new (NULL, NULL);
  gtk_widget_show (scrolledwindow1);
  gtk_fixed_put (GTK_FIXED (fixed16), scrolledwindow1, 88, 48);
  gtk_widget_set_size_request (scrolledwindow1, 624, 248);

  treeview2_nutrition = gtk_tree_view_new ();
  gtk_widget_show (treeview2_nutrition);
  gtk_container_add (GTK_CONTAINER (scrolledwindow1), treeview2_nutrition);
  gtk_widget_set_size_request (treeview2_nutrition, 568, 240);

  button_afficher_meilleur_M = gtk_button_new_with_mnemonic (_("Afficher"));
  gtk_widget_show (button_afficher_meilleur_M);
  gtk_fixed_put (GTK_FIXED (fixed16), button_afficher_meilleur_M, 272, 320);
  gtk_widget_set_size_request (button_afficher_meilleur_M, 152, 56);

  g_signal_connect ((gpointer) treeview2_nutrition, "row_activated",
                    G_CALLBACK (on_treeview2_nutrition_row_activated),
                    NULL);
  g_signal_connect ((gpointer) button_afficher_meilleur_M, "clicked",
                    G_CALLBACK (on_button_afficher_meilleur_M_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (meilleur, meilleur, "meilleur");
  GLADE_HOOKUP_OBJECT (meilleur, fixed16, "fixed16");
  GLADE_HOOKUP_OBJECT (meilleur, label130, "label130");
  GLADE_HOOKUP_OBJECT (meilleur, label132, "label132");
  GLADE_HOOKUP_OBJECT (meilleur, scrolledwindow1, "scrolledwindow1");
  GLADE_HOOKUP_OBJECT (meilleur, treeview2_nutrition, "treeview2_nutrition");
  GLADE_HOOKUP_OBJECT (meilleur, button_afficher_meilleur_M, "button_afficher_meilleur_M");

  return meilleur;
}

