/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

GtkWidget* create_windowGestionMenu (void);
GtkWidget* create_ModifierMenu (void);
GtkWidget* create_dialog1 (void);
GtkWidget* create_dialog2 (void);
GtkWidget* create_dialog3 (void);
GtkWidget* create_windowRemplir (void);
GtkWidget* create_windowAjoutMenu (void);
GtkWidget* create_ListeMenus (void);
GtkWidget* create_windowSupprimeMenu (void);
GtkWidget* create_meilleur (void);
