/*
 * Initial main.c file generated by Glade. Edit as required.
 * Glade will not overwrite this file.
 */

#ifdef HAVE_CONFIG_H
#  include <config.h>
#endif

#include <gtk/gtk.h>

#include "interface.h"
#include "support.h"

int
main (int argc, char *argv[])
{
  GtkWidget *windowGestionMenu;
  /*GtkWidget *windowModifierMenu;
  GtkWidget *windowSupprimeMenu;
  GtkWidget *ModifierMenu;
  GtkWidget *dialog1;
  GtkWidget *dialog2;
  GtkWidget *dialog3;
  GtkWidget *windowRemplir;
  GtkWidget *windowAjoutMenu;*/

#ifdef ENABLE_NLS
  bindtextdomain (GETTEXT_PACKAGE, PACKAGE_LOCALE_DIR);
  bind_textdomain_codeset (GETTEXT_PACKAGE, "UTF-8");
  textdomain (GETTEXT_PACKAGE);
#endif

  gtk_set_locale ();
  gtk_init (&argc, &argv);

  add_pixmap_directory (PACKAGE_DATA_DIR "/" PACKAGE "/pixmaps");

  /*
   * The following code was added by Glade to create one of each component
   * (except popup menus), just so that you see something after building
   * the project. Delete any components that you don't want shown initially.
   */
  windowGestionMenu = create_windowGestionMenu ();
  gtk_widget_show (windowGestionMenu);
 /* windowModifierMenu = create_windowModifierMenu ();
  gtk_widget_show (windowModifierMenu);
  windowSupprimeMenu = create_windowSupprimeMenu ();
  gtk_widget_show (windowSupprimeMenu);
  ModifierMenu = create_ModifierMenu ();
  gtk_widget_show (ModifierMenu);
  dialog1 = create_dialog1 ();
  gtk_widget_show (dialog1);
  dialog2 = create_dialog2 ();
  gtk_widget_show (dialog2);
  dialog3 = create_dialog3 ();
  gtk_widget_show (dialog3);
  windowRemplir = create_windowRemplir ();
  gtk_widget_show (windowRemplir);
  windowAjoutMenu = create_windowAjoutMenu ();
  gtk_widget_show (windowAjoutMenu);*/

  gtk_main ();
  return 0;
}

